name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image name
        run: |
          echo "REGISTRY=ghcr.io" >> $GITHUB_ENV
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push App image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app:latest

      - name: Build and push Websocket image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.websocket
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/websocket:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            REGISTRY="ghcr.io"
            REPO_NAME="${{ github.repository }}"
            IMAGE_NAME=${REPO_NAME,,}

            echo "Logging in to GHCR..."
            echo ${{ secrets.GHCR_READ_TOKEN }} | docker login ghcr.io -u syahrulapr86 --password-stdin

            echo "Preparing app directory..."
            mkdir -p ~/merman
            cd ~/merman

            echo "Pulling latest images..."
            docker pull $REGISTRY/$IMAGE_NAME/app:latest
            docker pull $REGISTRY/$IMAGE_NAME/websocket:latest

            echo "Deploying containers..."
            docker compose down
            docker compose up -d

            echo "Joining containers to proxy network..."
            /usr/local/bin/join-proxy-network.sh

            echo "Cleaning unused images..."
            docker image prune -f

            echo "Deployment finished successfully."
